ttg/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'ttg.views',
    url(r'files/by_version/(?P<version>current)/feed.zip$', 'feed_zip',
        name='feed_zip'),
    url(r'files/$', 'file_list', name='file_list'),
    url(r'files/(?P<mediafile_id>\d+)/current$', 'set_version',
        kwargs=dict(version='current'), name='set_current'),
)

ttg_app/urls.py
from django.conf import settings
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'ttg_app.ttg.views.home', name='home'),
    url(r'^ttg/', include('ttg_app.ttg.urls')),
)

if settings.ENABLE_ADMIN_DOCS:
    urlpatterns += patterns('',
        url(r'^admin/doc/', include('django.contrib.admindocs.urls')))

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls))
)

ttgsite/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'ttg.views.home', name='home'),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout', name='logout',
        kwargs={'next_page': reverse_lazy('home')}),
    url(r'^ttg/', include('ttg.urls')),
)

if settings.ENABLE_ADMIN_DOCS:
    urlpatterns += patterns(
        '', url(r'^admin/doc/', include('django.contrib.admindocs.urls')))

urlpatterns += patterns(
    '', url(r'^admin/', include(admin.site.urls))
)

if settings.DEBUG:
    urlpatterns += patterns(
        '', url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
                {'document_root': settings.MEDIA_ROOT}),
    )

ttg/models.py
from django.db import models
from django_extensions.db.models import TimeStampedModel


class MediaFile(TimeStampedModel):
    '''An uploaded or generated file'''
    MTTA_SIGNUP = u'S'
    GTFS_FILE = u'F'
    TYPE_CHOICES = (
        (MTTA_SIGNUP, 'MTTA Signup .zip'),
        (GTFS_FILE, 'GTFS Feed .zip'),
    )

    UPLOADED = u'u'
    GENERATED = u'g'
    SOURCE_CHOICES = (
        (UPLOADED, u'Uploaded'),
        (GENERATED, u'Generated'),
    )

    file = models.FileField(upload_to='ttg-media')
    file_type = models.CharField(max_length=2, choices=TYPE_CHOICES)
    source = models.CharField(max_length=30, choices=SOURCE_CHOICES)

    def __unicode__(self):
        return self.file.name

    def is_feed(self):
        return self.file_type == self.GTFS_FILE

    def is_current(self):
        return self.version_set.filter(name='current').exists()


class Version(TimeStampedModel):
    name = models.CharField(max_length=12)
    mediafile = models.ForeignKey('MediaFile')

ttg_project/ttg/models.py
from datetime import datetime
import os.path

from django.conf import settings
from django.db import models

class MediaFile(models.Model):
    '''An uploaded or generated file'''
    TYPE_CHOICES = (
        #(u'I', 'Import .zip'),
        (u'F', 'GTFS Feed .zip'),
    )
    
    TYPE_LOCAL_FORMATS = dict(
        #I='import.%s.zip',
        F='feed.%s.zip',
    )
    
    name = models.CharField(max_length=30)
    added_at = models.DateField()
    local_name = models.CharField(max_length=30)
    file_type = models.CharField(max_length=2, choices=TYPE_CHOICES)
    source = models.CharField(max_length=30)
    
    def save_upload(self, request_file, file_type='I'):
        if not self.added_at:
            self.added_at = datetime.now()
        if not self.file_type:
            self.file_type = file_type
        if not self.local_name:
            fmt = self.TYPE_LOCAL_FORMATS[self.file_type]
            self.local_name = fmt % self.added_at.strftime('%Y%m%d.%H%M')
        if not self.source:
            self.source = 'Uploaded'
        with open(self.abspath(), 'wb+') as destination:
            for chunk in request_file.chunks():
                destination.write(chunk)
        self.save()

    def abspath(self):
        return os.path.join(settings.MEDIA_ROOT, self.local_name)

ttg/forms.py
from django import forms

from mtta.tasks import import_mtta_signup
from ttg.models import MediaFile

import sys
if sys.version_info >= (2, 7, 0):
    from zipfile import is_zipfile
else:
    from zipfile import _EndRecData

    def _check_zipfile(fp):
        try:
            if _EndRecData(fp):
                return True         # file has correct magic number
        except IOError:
            pass
        return False

    def is_zipfile(filename):  # NOQA
        """Quickly see if a file is a ZIP file by checking the magic number.

        The filename argument may be a file or file-like object too.
        """
        result = False
        try:
            if hasattr(filename, "read"):
                result = _check_zipfile(fp=filename)
            else:
                with open(filename, "rb") as fp:
                    result = _check_zipfile(fp)
        except IOError:
            pass
        return result


class UploadFileForm(forms.ModelForm):
    '''Form for uploading a file'''

    class Meta:
        model = MediaFile
        fields = ('file_type', 'file')

    def clean_file(self):
        file = self.files['file']
        file.open()
        if not is_zipfile(file):
            raise forms.ValidationError('Uploaded files must be ZIP format.')
        return self.cleaned_data['file']

    def save(self, *args, **kwargs):
        self.instance.source = MediaFile.UPLOADED
        instance = super(UploadFileForm, self).save(*args, **kwargs)
        if instance.file_type == MediaFile.MTTA_SIGNUP:
            import_mtta_signup.delay(instance.id)
        return instance

ttg/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.servers.basehttp import FileWrapper
from django.http import HttpResponse
from django.shortcuts import redirect, render_to_response, get_object_or_404
from django.template import RequestContext

from forms import UploadFileForm
from models import MediaFile, Version


def home(request):
    '''View for the home page'''
    return render_to_response(
        'ttg/home.html',
        {},
        RequestContext(request))


def feed_zip(request, version):
    '''View for an output GTFS zip file'''
    feed = get_object_or_404(
        MediaFile, file_type=MediaFile.GTFS_FILE, version__name=version)
    wrapper = FileWrapper(feed.file)
    response = HttpResponse(wrapper, content_type='text/plain')
    response['Content-Length'] = feed.file.size
    return response


def set_version(request, version, mediafile_id):
    assert request.method == 'POST'
    mediafile = get_object_or_404(MediaFile, id=mediafile_id)
    Version.objects.filter(
        mediafile__file_type=mediafile.file_type, name=version).delete()
    Version.objects.get_or_create(name=version, mediafile=mediafile)
    return redirect('file_list')


@login_required
def file_list(request):
    '''View for files, including upload form'''
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.info(request,
                          'File uploaded as %s' % form.instance.file.name)
            return redirect('file_list')
    else:
        form = UploadFileForm()
    return render_to_response(
        'ttg/file_list.html',
        {'form': form, 'files': MediaFile.objects.all()},
        RequestContext(request))

ttg_project/ttg/views.py
from datetime import datetime

from django.conf import settings
from django.contrib import messages
from django.core.cache import cache
from django.core.urlresolvers import reverse
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext
import transitfeed

from forms import UploadFileForm
from models import MediaFile

def home(request):
    '''View for the home page'''
    return render_to_response(
        'ttg/home.html',
        {},
        RequestContext(request))


def feed_zip(request, version):
    '''View for an output GTFS zip file'''
    return HttpResponse('Not implemented yet')


def viewer(request, version):
    '''View for the schedule viewer'''
    current_feed = MediaFile.objects.filter(file_type='F').latest('added_at')
    schedule_key = 'schedule.%d' % current_feed.id 
    schedule = cache.get(schedule_key)
    if not schedule:    
        schedule = transitfeed.Schedule(
            problem_reporter=transitfeed.ProblemReporter())
        current_feed = MediaFile.objects.filter(
            file_type='F').latest('added_at')
        schedule.Load(current_feed.abspath())
        cache.set(schedule_key, schedule)

    return render_to_response(
        'ttg/viewer.html',
        {},
        RequestContext(request))


def file_list(request):
    '''View for files, including upload form'''
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.save_upload(request.FILES['upload'])
            messages.info(request,
                          'File uploaded as %s' % form.instance.local_name)
            form = UploadFileForm()
    else:
        form = UploadFileForm()
    return render_to_response(
        'ttg/file_list.html',
        {'form': form, 'files': MediaFile.objects.all()},
        RequestContext(request))

ttg/templates/ttg/base.html
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<title>{% block title %}TITLE NOT SET{% endblock %}</title>
{% block style %}
<link rel='stylesheet' href='{{ STATIC_URL }}css/ttg.css' >
{% endblock %}
{% block head %}{% endblock %}
</head>
<body>{% block body %}{% endblock %}</body>
</html>

ttg/templates/ttg/file_list.html
{% extends 'ttg/base.html' %}
{% load url from future %}
{% block title %}Files{% endblock %}
{% block body %}
<h1>Files</h1>
<p><a href="{% url 'home' %}">Back to Home</a></p>
<table>
    <tr><th>File Name</th><th>Date Added</th><th>Source</th><th>Current?</th></tr>
{% for f in files %}
<tr>
    <td><a href="{{f.file.url}}">{{f.file.name}}</td>
    <td>{{f.created}}</td>
    <td>{{f.get_source_display}}</td>
    <td>
        {% if f.is_feed %}
            {% if f.is_current %}
            <b>Current</b>
            {% else %}
            <form action="{% url 'set_current' f.id %}" method="POST">{% csrf_token %}<button type="submit">Set as current</button></form>
            {% endif %}
        {% endif %}
    </td>
</tr>
{% empty %}
<tr><td span=3><em>None</em></td></tr>
{% endfor %}
</table>

<h2>Upload New</h2>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<form method="post" enctype="multipart/form-data">
{{ form.as_p }}
{% csrf_token %}
<input type="submit" value="Submit" />
</form>
{% endblock %}

ttg/templates/ttg/home.html
{% extends 'ttg/base.html' %}
{% load url from future %}
{% block title %}Tulsa Transit as GTFS Feed{% endblock %}
{% block body %}
<h1>Tulsa Transit as GTFS</h1>
<p>
This is the <a href="http://tulsawebdevs.org/">Tulsa Web Devs'</a> project
to get <a href="http://tulsatransit.org/">Tulsa Transit's</a> route and
schedule data into the 
<a href="https://developers.google.com/transit/gtfs/reference">
General Transit Feed Specification</a> (GTFS), a necessary step to get Tulsa's
buses into
<a href="http://maps.google.com/maps?saddr=fab+lab&daddr=hardesty+library&hl=en&ll=36.08906,-95.920944&spn=0.159528,0.210457&sll=36.087805,-95.908445&sspn=0.15953,0.210457&geocode=Fd2cJwIdecpH-iHxn8YQoB5qiSldhY208-y2hzE9ZpWyKiQm0Q%3BFZ28JQIdVO9I-iEfZtX30cXLKimBDtSqDo62hzFWUu0ERxi5Vw&dirflg=r&ttype=now&noexp=0&noal=0&sort=def&mra=ltm&t=h&z=12&start=0">Google Maps</a>.
See
<a href="https://github.com/tulsawebdevs/tulsa-transit-google">
the project page</a> for more information.
</p>
<ul>
<li><a href="{% url 'feed_zip' version='current' %}">The current GTFS feed</a></li>
<li><a href="http://tripplanner.tulsawebdevs.org/">View the current GTFS data on a map</a></li>
{% if user.is_authenticated %}
<li><a href="{% url 'file_list' %}">View all files / Upload a new file</a></li>
{% if user.is_staff %}
<li><a href="/admin/">View the admin</a></li>
{% endif %}
<li><a href="{% url 'logout' %}">Logout</a></li>
{% else %}
<li><a href="{% url 'login' %}">Login</a></li>
{% endif %}
</ul>
{% endblock %}